# Generated by Django 5.1.4 on 2024-12-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='img',
            field=models.ImageField(default=0, upload_to='img'),
            preserve_default=False,
        ),
    ]
